version: '3'

services:
  dev:
    build: ./services/dev
    environment:
      - CDKTF_ENVIRONMENT=${CDKTF_ENVIRONMENT}
      - CDKTF_GOOGLE_CLOUD_LOCATION=${CDKTF_GOOGLE_CLOUD_LOCATION}
      - CDKTF_GOOGLE_CLOUD_PROJECT=${CDKTF_GOOGLE_CLOUD_PROJECT}
      - PHOENIX_DATABASE_PATH=${PHOENIX_DATABASE_PATH}
      - PHOENIX_SECRET_KEY_BASE=${PHOENIX_SECRET_KEY_BASE}
      - LITESTREAM_DATABASE_PATH=${LITESTREAM_DATABASE_PATH}
      - LITESTREAM_REPLICA_URL=${LITESTREAM_REPLICA_URL}
    volumes:
      - ../:/workspace
