version: '3'

services:
  dev:
    build: ./services/dev
    environment:
      - CDKTF_BACKEND_BUCKET=${CDKTF_BACKEND_BUCKET}
      - CDKTF_ENVIRONMENT=${CDKTF_ENVIRONMENT}
      - CDKTF_LOCATION=${CDKTF_LOCATION}
      - CDKTF_PREFIX=${CDKTF_PREFIX}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - LITESTREAM_DATABASE_PATH=${LITESTREAM_DATABASE_PATH}
      - LITESTREAM_REPLICA_URL=${LITESTREAM_REPLICA_URL}
      - PHOENIX_DATABASE_PATH=${PHOENIX_DATABASE_PATH}
      - PHOENIX_SECRET_KEY_BASE=${PHOENIX_SECRET_KEY_BASE}
    volumes:
      - ../:/workspace
